월드컵 결과 화면 개발
DaeJol/catdogcup pull request #25
Opened 2024-07-13 09:24 UTC by betterafter

## Job title

## What did you do? or What Will you do?

- [ ] task 1
- [ ] task 2
- [ ] task 3
- [ ] task 4
- [ ] task 5
- [ ] task 6
- [ ] task 7
- [ ] task 8

## work result

## code discussion / review request / concern

2024-07-19 08:45 UTC, Hyesung82 requested changes

2024-07-19 08:45 UTC, Hyesung82 commented on domain/src/main/java/di/UsecaseModule.kt
> +    fun provideGetImageUsecase(
pascal case를 사용하는 게 좋을 것 같습니다
Usecase -> UseCase

2024-07-19 08:45 UTC, Hyesung82 commented on domain/src/main/java/usecase/GetImageUsecase.kt
> +            val flow = dogImagesRepository.getDogRandomImages(randomImageCount).map {
중요한건 아니지만 flow 변수 선언 안하고 return dogImageRepository.~처럼 바로 반환해도 될듯?

2024-07-19 08:45 UTC, Hyesung82 commented on presentation/src/main/java/com/daejol/presentation/main/MainScreen.kt
> +fun MainScreen() {
다른 PR에도 언급했지만 ~App이라고 네이밍하는 게 더 직관적이지 않을까요..?

2024-07-19 08:45 UTC, Hyesung82 commented on presentation/src/main/java/com/daejol/presentation/worldcup/play/WorldCupPlayScreen.kt
> +    Column(
가능하다면 이 Column 내의 요소들을 별도의 Composable로 나누면 보기 좋을 것 같습니다

2024-07-19 08:45 UTC, Hyesung82 commented on presentation/src/main/java/com/daejol/presentation/worldcup/result/WorldCupResultScreen.kt
> +    Column(
여기도 내부 요소들을 별도의 함수로 나누면 좋을듯!

2024-07-21 10:15 UTC, betterafter commented on presentation/src/main/java/com/daejol/presentation/worldcup/result/WorldCupResultScreen.kt
> +    Column(
확인했습니다! 일단 핵심 버튼 3개와 다른 월드컵 하러 가기에 대해서 분리했습니다. 다른 컨텐츠는 분리가 필요할 지에 대해 추후 고려 후 수정 예정!

2024-07-23 08:33 UTC, merged